/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISignalingMultiOffer,
  ISignalingMultiOfferInterface,
} from "../../contracts/ISignalingMultiOffer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "offerer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "answerer",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "signal",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "creationTime",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Signal",
        name: "answer",
        type: "tuple",
      },
    ],
    name: "proposeAnswer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "peer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "offerer",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "signal",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "creationTime",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct Signal",
        name: "offer",
        type: "tuple",
      },
    ],
    name: "proposeOffer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "offerer",
        type: "address",
      },
      {
        internalType: "address",
        name: "answerer",
        type: "address",
      },
    ],
    name: "getAnswer",
    outputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "signal",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "creationTime",
            type: "uint256",
          },
        ],
        internalType: "struct Signal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "offerer",
        type: "address",
      },
      {
        internalType: "address",
        name: "answerer",
        type: "address",
      },
    ],
    name: "getOffer",
    outputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "signal",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "creationTime",
            type: "uint256",
          },
        ],
        internalType: "struct Signal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "answer",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "peer",
        type: "address",
      },
    ],
    name: "setAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "offer",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "peer",
        type: "address",
      },
    ],
    name: "setOffer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISignalingMultiOffer__factory {
  static readonly abi = _abi;
  static createInterface(): ISignalingMultiOfferInterface {
    return new Interface(_abi) as ISignalingMultiOfferInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISignalingMultiOffer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISignalingMultiOffer;
  }
}
