/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1967 from "./ERC1967.js";
export type { erc1967 };
import type * as beacon from "./beacon.js";
export type { beacon };
